export const CROP_COLOR_DICTIONARY = {
  cereals: '#d95997',
  pulses_leguminous: '#1230a5',
  roots_tubers: '#32866d',
  fruit_nuts: '#ffe01b',
  oilseed_crops: '#6e23bd',
  sugar_crops: '#ccf517',
  fibres: '#6582a5',
  stimulants: '#45539d',
  vegetables: '#99c960',
  other_crops: '#dc3355'
};

export const CROP_OPTIONS = [
  { value: 'all', label: 'All crops' },
  { value: 'arabica coffee', label: 'Arabica coffee', color: CROP_COLOR_DICTIONARY.stimulants },
  { value: 'banana', label: 'Banana', color: CROP_COLOR_DICTIONARY.fruit_nuts },
  { value: 'barley', label: 'Barley', color: CROP_COLOR_DICTIONARY.cereals },
  { value: 'bean', label: 'Bean', color: CROP_COLOR_DICTIONARY.pulses_leguminous },
  { value: 'cassava', label: 'Cassava', color: CROP_COLOR_DICTIONARY.roots_tubers },
  { value: 'chickpea', label: 'Chickpea', color: CROP_COLOR_DICTIONARY.pulses_leguminous },
  { value: 'cocoa', label: 'Cocoa', color: CROP_COLOR_DICTIONARY.stimulants },
  { value: 'coconut', label: 'Coconut', color: CROP_COLOR_DICTIONARY.oilseed_crops },
  { value: 'cotton', label: 'Cotton', color: CROP_COLOR_DICTIONARY.fibres },
  { value: 'cowpea', label: 'Cowpea', color: CROP_COLOR_DICTIONARY.pulses_leguminous },
  { value: 'groundnut', label: 'Groundnut', color: CROP_COLOR_DICTIONARY.oilseed_crops },
  { value: 'lentil', label: 'Lentil', color: CROP_COLOR_DICTIONARY.pulses_leguminous },
  { value: 'maize', label: 'Maize', color: CROP_COLOR_DICTIONARY.cereals },
  { value: 'millet', label: 'Millet', color: CROP_COLOR_DICTIONARY.cereals },
  { value: 'oilpalm', label: 'Oilpalm', color: CROP_COLOR_DICTIONARY.oilseed_crops },
  { value: 'other cereals', label: 'Other cereals', color: CROP_COLOR_DICTIONARY.cereals },
  { value: 'other fibre crops', label: 'Other fibres', color: CROP_COLOR_DICTIONARY.fibres },
  { value: 'other pulses', label: 'Other pulses', color: CROP_COLOR_DICTIONARY.pulses_leguminous },
  { value: 'other roots', label: 'Other roots', color: CROP_COLOR_DICTIONARY.roots_tubers },
  { value: 'other oil crops', label: 'Other oil crops', color: CROP_COLOR_DICTIONARY.oilseed_crops },
  { value: 'potato', label: 'Potato', color: CROP_COLOR_DICTIONARY.roots_tubers },
  { value: 'pearl millet', label: 'Pearl millet', color: CROP_COLOR_DICTIONARY.cereals },
  { value: 'pigeonpea', label: 'Pigeonpea', color: CROP_COLOR_DICTIONARY.pulses_leguminous },
  { value: 'plantain', label: 'Plantain', color: CROP_COLOR_DICTIONARY.fruit_nuts },
  { value: 'rapeseed', label: 'Rapeseed', color: CROP_COLOR_DICTIONARY.oilseed_crops },
  { value: 'rice', label: 'Rice', color: CROP_COLOR_DICTIONARY.cereals },
  { value: 'rest of crops', label: 'Rest of crops', color: CROP_COLOR_DICTIONARY.other_crops },
  { value: 'robusta coffee', label: 'Robusta coffee', color: CROP_COLOR_DICTIONARY.stimulants },
  { value: 'sesameseed', label: 'Sesameseed', color: CROP_COLOR_DICTIONARY.oilseed_crops },
  { value: 'small millet', label: 'Small millet', color: CROP_COLOR_DICTIONARY.cereals },
  { value: 'sorghum', label: 'Sorghum', color: CROP_COLOR_DICTIONARY.cereals },
  { value: 'soybean', label: 'Soybean', color: CROP_COLOR_DICTIONARY.oilseed_crops },
  { value: 'sugarbeet', label: 'Sugarbeet', color: CROP_COLOR_DICTIONARY.sugar_crops },
  { value: 'sugarcane', label: 'Sugarcane', color: CROP_COLOR_DICTIONARY.sugar_crops },
  { value: 'sunflower', label: 'Sunflower', color: CROP_COLOR_DICTIONARY.oilseed_crops },
  { value: 'sweet potato', label: 'Sweet potato', color: CROP_COLOR_DICTIONARY.roots_tubers },
  { value: 'tea', label: 'Tea', color: CROP_COLOR_DICTIONARY.stimulants },
  { value: 'temperate fruit', label: 'Temperate fruit', color: CROP_COLOR_DICTIONARY.fruit_nuts },
  { value: 'tobacco', label: 'Tobacco', color: CROP_COLOR_DICTIONARY.stimulants },
  { value: 'tropical fruit', label: 'Tropical fruit', color: CROP_COLOR_DICTIONARY.fruit_nuts },
  { value: 'vegetables', label: 'Vegetables', color: CROP_COLOR_DICTIONARY.vegetables },
  { value: 'wheat', label: 'Wheat', color: CROP_COLOR_DICTIONARY.cereals },
  { value: 'yams', label: 'Yams', color: CROP_COLOR_DICTIONARY.roots_tubers }
];

export default {
  CROP_OPTIONS,
  CROP_COLOR_DICTIONARY
};
