// MODAL
export const MODAL_TOGGLE = 'MODAL_TOGGLE';
export const MODAL_SET_OPTIONS = 'MODAL_SET_OPTIONS';
export const MODAL_LOADING = 'MODAL_LOADING';

// TOOLTIP
export const TOOLTIP_TOGGLE = 'TOOLTIP_TOGGLE';
export const TOOLTIP_SET_CHILDREN = 'TOOLTIP_SET_CHILDREN';
export const TOOLTIP_LOADING = 'TOOLTIP_LOADING';
export const TOOLTIP_SET_CHILDREN_PROPS = 'TOOLTIP_SET_CHILDREN_PROPS';
export const TOOLTIP_SET_POSITION = 'TOOLTIP_SET_POSITION';
export const TOOLTIP_FOLLOW_TOGGLE = 'TOOLTIP_FOLLOW_TOGGLE';
