// MODAL
export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';
export const MODAL_SET_CHILDREN = 'MODAL_SET_CHILDREN';
export const MODAL_LOADING = 'MODAL_LOADING';
export const MODAL_READY = 'MODAL_READY';
export const MODAL_SET_CHILDREN_PROPS = 'MODAL_SET_CHILDREN_PROPS';
